FROM rust:1.82-bullseye as builder

WORKDIR /usr/src/rust-quest-tracker
COPY . .
RUN cargo install --path .

FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev \
    libpq-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/cargo/bin/rust-quest-tracker /usr/local/bin/rust-quest-tracker

CMD ["rust-quest-tracker"]